.TH WOLFETCH 5 "August 2026" "wolfetch 0.5.0-pre.5" "File Formats"
.SH NAME
wolfetch \- wolfetch configuration file
.SH DESCRIPTION
The configuration file uses one key=value pair per line.
.SH EXAMPLE
.nf
theme=royal
show=distro,kernel,host,cpu,memory,disk,uptime
logo=wolf
show_runtime=true
show_process_memory=true
.fi
.SH FIELDS
Fields include distro, kernel, host, wm, term, shell, cpu, cpu_usage, gpu,
display order.
